import enum

from telegram.ext import ConversationHandler


class States(enum.Enum):
    MENU = "MENU"
    BACK = "BACK"
    NEXT_PAGE = "NEXT_PAGE"
    PREV_PAGE = "PREV_PAGE"
    ASK_FOR_INPUT = "ASK_FOR_INPUT"
    TYPING = "TYPING"
    CHARACTERS = "CHARACTERS"
    COMICS = "COMICS"
    SERIES = "SERIES"
    EVENTS = "EVENTS"
    LIST_CHARACTERS = "LIST_CHARACTERS"
    FIND_CHARACTER_BY_NAME = "FIND_CHARACTER_BY_NAME"
    FIND_CHARACTER_BY_NAME_BEGINNING = "FIND_CHARACTER_BY_NAME_BEGINNING"
    LIST_COMICS = "LIST_COMICS"
    FIND_COMIC_BY_TITLE = "FIND_COMIC_BY_TITLE"
    FIND_COMIC_BY_TITLE_BEGINNING = "FIND_COMIC_BY_TITLE_BEGINNING"
    LIST_EVENTS = "LIST_EVENTS"
    FIND_EVENT_BY_NAME = "FIND_EVENT_BY_NAME"
    FIND_EVENT_BY_NAME_BEGINNING = "FIND_EVENT_BY_NAME_BEGINNING"
    LIST_SERIES = "LIST_SERIES"
    FIND_SERIES_BY_TITLE = "FIND_SERIES_BY_TITLE"
    FIND_SERIES_BY_TITLE_BEGINNING = "FIND_SERIES_BY_TITLE_BEGINNING"
    END = str(ConversationHandler.END)
